baseURL = "https://marsettler.com/"
languageCode = "en-us"
title = "Marsettler"
theme = "hugo-dusk"
disableHugoGeneratorInject = true
enableGitInfo = true

[params]
	github = "hueypark"
	twitter = "jaewanHueyPark"
	email = "jaewan.huey.park@gmail.com"

[[menu.main]]
	name = "Wiki"
	weight = -120
	identifier = "wiki"
	url = "/wiki/"

[[menu.main]]
	name = "About Me"
	weight = -110
	identifier = "about me"
	url = "/about-me/"