baseURL = "https://marsettler.com/"
languageCode = "en-us"
title = "Marsettler"
theme = "hugo-dusk"
disableHugoGeneratorInject = true

[params]
	github = "hueypark"
	twitter = "jaewanHueyPark"
	email = "jaewan.huey.park@gmail.com"